# Change these first
owner: r2fresh # Your GitHub username
repo: chelsea # Your Github repository name

# Add your sites here
sites:
  - name: Chelsea
    url: http://chelsea.kt.co.kr
  - name: KTDN
    url: http://ktdn.chelsea.kt.co.kr
  - name: Gitlab
    url: http://scm.chelsea.kt.co.kr
  - name: Orchestra
    url: http://issue.chelsea.kt.co.kr
  - name: Nexus
    url: http://repo.chelsea.kt.co.kr
  - name: Jenkins
    url: http://build.chelsea.kt.co.kr
  - name: Ansible
    url: http://deploy.chelsea.kt.co.kr/#/login
  - name: MatterMost
    url: http://chat.chelsea.kt.co.kr/login
  - name: Xwiki
    url: http://wiki.chelsea.kt.co.kr/xwiki/bin/view/Main/
  - name: SonarQube
    url: http://codeanlys.chelsea.kt.co.kr/sessions/new?return_to=%2F
  - name: Reviewboard
    url: http://codeanlys.chelsea.kt.co.kr/sessions/new?return_to=%2F
  - name: kt-chelsea
    url: https://kt-chelsea.github.io/
    
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /chelsea
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Chelsea Statistics
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
